# -*- coding: utf-8 -*-
"""lambda_function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ObZiv-qw07hcZHtpo3jeIwcVX1XC4dJ3
"""

import boto3

s3 = boto3.client('s3')

def lambda_handler(event, context):
    # Get the uploaded file details from the event object
    bucket = event['Records'][0]['s3']['bucket']['name']
    key = event['Records'][0]['s3']['object']['key']

    # Download the file to a temporary location
    temp_file = '/tmp/' + key
    s3.download_file(bucket, key, temp_file)

    # Validate the file type
    if is_pdf(temp_file):
        extracted_data = extract_text_from_pdf(temp_file)
    elif is_image(temp_file):
        extracted_data = extract_text_from_image(temp_file)
    else:
        return {
            'statusCode': 400,
            'body': 'Invalid file type. Only PDF and image files are supported.'
        }

    # Save the extracted data to a database or file
    save_data(extracted_data)

    return {
        'statusCode': 200,
        'body': 'File processed successfully.'
    }