# -*- coding: utf-8 -*-
"""s3_setup.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AgHUoBiEyuMtG4cKAQghMVb_oqNYJ7Kl
"""

import boto3

s3 = boto3.client('s3')

bucket_name = 'your-bucket-name'

# Create the S3 bucket
s3.create_bucket(Bucket=bucket_name)